### ISSUE TITLE
Coordinar traducción

### ISSUE THREAD

**Issue by caballerof** [javascript-tutorial/es.javascript.info#1]
@lizzie136 Saludos, espero todo vaya bien, quisiera preguntarte como nos coordinamos para el trabajo de traducción del tutorial de JS, podría iniciar desde la principio o si es mas conveniente tomar una sección en especifico. 

¿Habría posibilidad de tener un canal de comunicación mas directo?

**Comment by lizzie136** [comment]
Hola @caballerof, claro, te parece por Slack? o por gmail? eportillaf@gmail.com

**Comment by victorze** [comment]
Hola @lizzie136, me gustaría encargarme de la traducción de la parte dos. Y quisiera saber en cual rama vamos a trabajar ya que existen 2.

**Comment by lizzie136** [comment]
Hola @victorze a que parte te refieres con parte 2? La parte de *2-ui* ?  Si es esa por mi lado esta mas que cool :)

**Comment by lizzie136** [comment]
Estoy probando algo nuevo, les parece conectarse a este server de discourse https://discord.gg/WPcsf6 ?

**Comment by victorze** [comment]
Ok, ya estoy dentro :)
