### ISSUE TITLE
Ingresar bloque de código en mi artículo

### ISSUE THREAD

**Issue by aarrieth** [javascript-tutorial/es.javascript.info#130]
Buenas tardes.
¿cómo hago para ingresar bloques de código en mi artículo de traducción?
Lo estoy haciendo desde mi repositorio.

**Comment by panterx-js** [comment]
Los artículos están escritos en Markdown. Para escribir un bloque de código solo tenes que hacer 4 espaciados y lo que escribas después ya aparecerá en un bloque de código.

**Comment by ricardov03** [comment]
Agregando valor al comentario de Federico, puedes hacerlo también utilizando el siguiente formato:

```[Lenguaje] (Ojo: Sin los brackets)
[Codigo]
```

Ejemplo real:

```javascript
let var = ’This is a variable’
```
