### ISSUE TITLE
Año 2020, estamos trabajando sobre versiones de capítulos muy viejas

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#201]
Hay correcciones de texto y ejercicios,
más las novedades del lenguaje y nuevos capítulos
Sugiero sincronizar los capítulos aún no marcados por traductores.

**Comment by vplentinax** [comment]
Hola @joaquinelio, ya  una persona se está encargando de la sincronización y actualización del repositorio para que sea igual a la versión en ingles. Realmente, todos estamos traduciendo desde la versión en inglés. Incluso, si hay articulos o elementos que no aparecen en el de ingés, se deben eliminar de la traducción para que sean totalmente iguales. También tenemos un servidor en Discord donde nos coordinamos  y compartimos sobre el proceso de la traducción. Te dejo el link [Discord Server](: https://discord.gg/PckggG) 

Un saludo

**Comment by joaquinelio** [comment]
AAhh!
It's ALIVE!
uh... sorry, @vplentinax ... la cuarentena me tiene mal. 

¡Hola! Y gracias.  Creí que estaba muerto por las fechas de eventos importantes del proyecto,
pensé que las traducciones eran de entusiastas que no irían a parar a ningún lado.
 igual subí dos PR que tenía de hace un año frenadas por mis desvaríos git ahora cuarentenarreglados.

No estaba haciendo caso al ruego de CONTRIBUTING.md para que me enganchara,
la primera vez que pregunté me pusieron

> oct2019
> Hi @joaquinelio, Trello and discourse were our first try to organize this repository before the javascript.info organization was created and this issue was open. So at the moment, it is obsolete.
> 

Don bot parece pragmático, ¿qué tiene de malo?

Bueno, me alegro de que respire, espero ver merges en el 
mejor y más completo curso del mundo para el peor lenguaje de la modernidad.

Salud y pizzetas.
![66043296-2cb9b800-e4f5-11e9-9bc1-845e346b2212](https://user-images.githubusercontent.com/6558304/82722370-8a755d00-9c9c-11ea-903f-f9d7bb02da08.png)

**Comment by joaquinelio** [comment]
No encuentro mucho sentido en abandonar git y duplicar la misma información en discord y llevar las discusiones allá lejos :) 

Hubiera recomendado 

* un README-ES.md para nuestro uso exclusivo con los recursos que vamos encontrando y  las recomendaciones propias del lenguaje.
   
* un GLOSARIO-ES.md , simple lista alfabética que (via PR) alimentaríamos todos y su correspondiente  issue para  su discusión, 
Todos pueden traducir, pero es necesario que el revisor entienda JS bastante, y un glosario propio de fácil acceso evitaría muchos problemas en lugar de rastrear varios chats o andar preguntando lo mismo.

Como sea, NO me postulo maintainer, por lo tanto apoyo cualquier iniciativa que haga reflotar esto, y mi saludo cordial a todo el que pone su trabajo para ayudar.

Salud y pizzetas
Elio

**Comment by joaquinelio** [comment]
Saludos, @vplentinax the hard worker 

Antes de que sigas sumando trabajos nuevos (miré un par y son muy buenos), sugiero que intentes otro, el de REVIEW.   Ahí vas a entender por qué insisto con la actualización del upstream.  

El review debería ser fácil, es solo ver el DIFF y seguir los colores,  pero hoy no lo es, y en uno largo o con varios task /solution  se vuelve muy engorroso hacer el seguimiento.  Tampoco mortal, pero no es NADA difícil hacerlo fácil, ¿para qué el incordio entonces?  

Prioridades.

Para empezar, (solo maintainers) actualizar nuestra base:  Facilita solo un poco la traducción pero mucho más el review.  Digo primero porque 
1) Facilitarpia de forma inmediata toda traducción y review que se hagan a partir de ella
2) evitaría que los nuevos que se meten en el proyecto (como yo ¡hace 1 año! O @maksumi el más reciente) desperdicien trabajo y se tenga que hacer de nuevo.

La actualización no sería NADA difícil si se hiciera regularmente, pero ahora es más laborioso porque las mejoras en inglés son más nuevas que algunas traducciones. El criterio es actualizar solo las no reclamadas, algo que no parece que se pueda hacer automáticamente.
 
Luego MERGE (¡8 meses sin!).  Atender los PR, pero para ello: reviews.  Hay decenas de PR colgados ahora, es decir, casi el doble en reviews por hacer y sin colorcitos.
 
Este proyecto no necesita un superlíder como maintainer, solo uno más estable.  Y que tenga más claro GIT, lástima no me siento calificado. Me confieso culpable de no meterme más en esto y solo criticar, pero viendo tu furia productiva me duele que no se aproveche.
