### ISSUE TITLE
Contributions without CLA

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#234]
Hi, @iliakan 
@vplentinax @ezzep66
There are old PR and some MERGED PR without the CLA agreement signed.
As a no-charge explicit grant, It seems important. 
If we can't reach the authors, should we erase the articles from the final site?

**Comment by iliakan** [comment]
CLA is only really required for essential authorship. CLA is an official permission to republish, but if that's a typo fix or grammar fix, then no such permission is required. 

So if you're talking about English tutorial, then that's not a problem, as it's authored by me.

If you're talking about the Spanish translation, then CLA is needed. 

But even if CLA isn't there, I feel it's not enough reason to delete the PR, as the author's intent was to submit it for the public usage, they just forgot to sign it.

**Comment by joaquinelio** [comment]
> If you're talking about the Spanish translation, then CLA is needed.
> 
> But even if CLA isn't there, I feel it's not enough reason to delete the PR, as the author's intent was to submit it for the public usage, they just forgot to sign it.

* Spanish translation issue.
* Public usage contribution. I guess it is clear from the start, but I'm not a lawyer.

@vplentinax @ezzep66 
Well, partners, we can continue reviewing those too...
