### ISSUE TITLE
La invitación al servidor de Discord ya no es válida

### ISSUE THREAD

**Issue by ddanielcruzz** [javascript-tutorial/es.javascript.info#235]
Estoy interesado en ayudar a actualizar el repositorio, pero al intentar ingresar a Discord me indica que la invitación no es válida. 

![Captura de Pantalla 2020-06-08 a la(s) 16 51 46](https://user-images.githubusercontent.com/20308945/84084076-6b6b1080-a9a8-11ea-9bcb-9ab66ba53251.png)

**Comment by joaquinelio** [comment]
https://discord.gg/BhSp5Q
dice que expira en un día
