### ISSUE TITLE
Corregir 1 8 3  Native prototypes (@cortizg)

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#291]
Native prototypes

Cerré con merge #193 sin aprobar para no perder la traducción y lo eliminé el issue17 pero sigue asignado a
@cortizg  
ahora nuestro repo tiene tu español, deberías hacer un nuevo pr sobre él

ups! no deja asignarlo porque no sos miembro

 1-8-3-2 solution, 
está bien pero falta borrar las lineas en inglés, tiene 20 lineas de más

1 8 3 article
16 genera la cadena `"[objeto Objeto]"`   debería ser `"[objet Objet]"` porque es lo que muestra el alert
148 no me convence "polirrelleno", polyfill es el soft que implementa compatibilidad y lo tomaría como nombre propio 

#193
tamb tiene algun coment de arreglo tuyos, podes revisarlos

**Comment by ezzep66** [comment]
no es el lugar para discutir problemas de los PR. 
Cierro.
Trasladar discusion de PR en PR por favor

**Comment by joaquinelio** [comment]
@ezzep66   "Cierro" ¿?

ESTE es el lugar para discutir issues.
Si no entendisste el problema, deberias dejar que siguiera su curso. 

Esto lo usamos poco 
porque son pocas las necesidades del proyecto sin código 
porque usamos demasiado discord,
porque un buen diseño del bot nos releva de andar coordinando todo (aunque a veces lo trampeamos pero justamente para que Don Bot siga en control).

**Comment by ezzep66** [comment]
No veo la razón de inicar Issue si puedes hacer los comentarios relacionados al PR #193 directamente ahí

[Pull Request](https://github.com/javascript-tutorial/es.javascript.info/pull/193)

**Comment by cortizg** [comment]
LISTO! PR #292 @joaquinelio

**Comment by joaquinelio** [comment]
> No veo la razón de inicar Issue si puedes hacer los comentarios relacionados al PR #193 directamente ahí
> 
> [Pull Request](https://github.com/javascript-tutorial/es.javascript.info/pull/193)

'cuz is an issue que lo trasciende.  
193 no va más
Es donde se plasman los issues, se asignan, resuelven y cierran.
