### ISSUE TITLE
Translations done needing update

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#307]
@iliakan 
Ok, we need to update the article

Is this on purpose?
![image](https://user-images.githubusercontent.com/6558304/87860989-48713c00-c918-11ea-8eaf-dd8552531175.png)

**Comment by joaquinelio** [comment]
Kicking the goal line away is not fair.

Tramposillo.
¡Pero aún podemos celebrar que superamos la mitad del repo!  🍰
@vplentinax  @ezzep66  @maksumi @cortizg +otros

**Comment by joaquinelio** [comment]
@vplentinax  y si ahora alguien lo tomara, no veria diferencia... ni con pr gringas  ni pr valentinas
este guy no da paz

**Comment by iliakan** [comment]
Changed that, cause `if` isn't an operator technically.

**Comment by joaquinelio** [comment]
1) I got that, I was just asking about erasing translator.  
  Is it just a progress control?  Every single change (not just the title) should do that then, erase PR & translator  (yes, if you erase one, you have to erase both) 

2) Any reason to reopen it? If it is ok, we just have to retake it. 
 There is only a "funny" (kicking goal line) comment to who supervise the syncs.

**Comment by iliakan** [comment]
So, the question is about the issue modification? Or.. I'm not sure I'm getting it, sorry.

The progress issue text is modified by bot. You can modify it manually as well.

**Comment by joaquinelio** [comment]
oh, sorry.  It's not a big deal, just wanted to know the why.
I know it was the bot.  I just expected it changed only the title, not translator and PR#. 

And  we DID change it manually a LOT.  Closed PR's,  articles taken and unattended for months, wrong/ very outdated/incomplete  translations, etc.  Still do.  Bot never complains... : )

**Comment by joaquinelio** [comment]
@iliakan 
Sorry to disturb you again, just a couple of questions about the "progress issue" format:

1) Does the @translator and #PR there have any purpose once the translation is closed {X]  ?

We noticed when an article changes its name, Mr.Bot updates the issue 
by removing it and adding a new one.  I guess it's ok,  "he" 
*just erase nonexistent articles and 
*adds the fresh ones. 
but then it forgets the [X] translated condition when it just needs a small update (like everywhere else)
2) Should we worry about it?

**Comment by iliakan** [comment]
1. No purpose, just for logging, but that's not really needed, as git itself keeps the logs.
2. So it removes all [X]s?

**Comment by joaquinelio** [comment]
@iliakan 
> 2. So it removes all [X]s? Or some of them?

No, not all of them.   Just the one with the title changed (as an effect of removing then adding the article) so: 
It Removes  [X],  @translator,  #PR,   That's why I asked about the log.   
It just kicks the goal line 1 step away...?  That's all?  No harm? Funny Bot.
Some people worried because it is nice to have the translator name there. I kind of credit.

Unrelated to this, we think we are ready, 1rst section pretty complete, really good for new learners...
They are GOOD translations. 
Do we need to do something?

**Comment by iliakan** [comment]
So, when an article is updated, the bot removes `[x]`, translator name, PR#?

**Comment by joaquinelio** [comment]
uhg... I think I'll let explanations to someone less... rambling, sorry about that.

>So, when an article is updated, the bot removes  [x], translator name, PR#?
No, 
 
This:
**when an article's TITLE is updated, the bot removes  [x], translator name, PR#**

that's all  what it does
(please refer to the img at the top comment)
No harm I guess,  I keep an eye on the list.
I just check [X] it again.  That is enough I guess.

**Comment by iliakan** [comment]
Thanks, finally got it!

Renaming an article is a rare thing, right now the bot doesn't track renames. They are difficult to track.

So it considers it a "removal + new article", hence the actions.

When we calculate the percentage of translation (for stats), mostly-translated articles to count as translated. So that doesn't shift the goal.

Indeed, you can update the title and manually click `[x]`.

So, I'll plan to deploy ES soon? Will make another issue for that then.

**Comment by joaquinelio** [comment]
YES!!   Prepare it. Tutorial -ES- ready to launch.
