### ISSUE TITLE
Don Bot te borró de Variable scope, closure

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#344]
@vplentinax 
Hi partner

Querras supongo actualizar esto, 
el bot te borró cuando le cambió el nombre

El original cambió el nombre al art y agregó unas líneas  "hours ago"
lo corregiria si no estuviera medio dormido

Lo marqué como hecho para que no sea tomado

, querrás ponerle tu nombre de nuevo tambien al issue17

**Comment by EzequielCaste** [comment]
fixed Variable scope, closure (@vplentinax) #178

**Comment by joaquinelio** [comment]
Este es un issue,
@EzequielCaste  Los issues no se solucionan ignorando el problema
#178 es historia antigua, qué tiene que ver aqui

@vplentinax tiene que enterarse del problema si quiere lo arregla,
 si no quizas lo arregle yo, 
o el que quiera, o nadie

**Comment by joaquinelio** [comment]
sin Valentina ya
quedara relegado.
