### ISSUE TITLE
Ready to go online

### ISSUE THREAD

**Issue by EzequielCaste** [javascript-tutorial/es.javascript.info#346]
Hi @iliakan 👋 

With 115 of 174 articles already translated, we are ready to go online, if you consider appropriate. 🚀 

Let us know what you think ;)

Cheers!

**Comment by iliakan** [comment]
Yeah, let's do that! =)

Please translate these YAML files (engine localizations for Spanish):

[locales.zip](https://github.com/javascript-tutorial/es.javascript.info/files/5060447/locales.zip)

**Comment by EzequielCaste** [comment]
Ok great! 
I'm working on it 👍

**Comment by EzequielCaste** [comment]
[locales.zip](https://github.com/javascript-tutorial/es.javascript.info/files/5063115/locales.zip)

Done! 🎉

**Comment by joaquinelio** [comment]
I'll start a big pull from EN.

maints, I'll leave ya this, click the delousing monkey:
articles left,  date claimed
https://joaquinelio-zone17.glitch.me/

wishing many young folks learning here...

**Comment by iliakan** [comment]
Please take a look at https://es.javascript.info/

**Comment by EzequielCaste** [comment]
Looking great!!

:) Happy to finally see some progress after all this time.

**Comment by iliakan** [comment]
I enabled CI, so any pushes to this repo get to the site automatically.

**Comment by iliakan** [comment]
I'm also going to add translation leads to the page https://es.javascript.info/about

BTW, is it true? @vplentinax did more than 50% of the translation?

**Comment by EzequielCaste** [comment]
@vplentinax she did the sincronization of the old translated files to the newer versions. Updating old translations.

I hope contributors names were not lost in the process.

**Comment by iliakan** [comment]
The contributor for each line is tracked by git. You must have heard about the `git blame` command.

So when files are moved around, created/deleted/committed by another person, this information may be changed. That's probably what happened.

**Comment by EzequielCaste** [comment]
BTW, I've changed my username in Github from ezzep66 to EzequielCaste. Is is possible to update it in the about page?

**Comment by iliakan** [comment]
To fix that, an article should be fully recommitted, right now (late evening) no bright ideas about that, maybe you can suggest something?

@EzequielCaste it's quite difficult to change without recommitting. The author info is stored in Git repo, not on github. It's a part of the commit hash.

**Comment by joaquinelio** [comment]
> The contributor for each line is tracked by git. You must have heard about the `git blame` command.
> 
> Usually it's reliable. But if an operation forces git to recognize the file as a new one, then the authorship for all lines is updated to the committer.
> 
> That's probably what has happened. Definitely not good.

"Blame" should be useful, but it is nearly empty for many files here. I didn't care too much.    
But.
I wonder if this is what causes a problem I'm dealing with now. 
Pulling from English upstream tries to OVERWRITE SOME traslated files. NO conflicts shown.
I CAN'T TRUST IT!  We need a trustworthy sync method, we shouldnt do it manually with our eyes. 

I have 3 remotes, origin, upstrem (es) enstream (en)
merge upstream, ok
then
merge enstream, lots of conflicts, ok 
but some files are replaced by english version with no conflict at all

D:\js\es.javascript.info\1-js\99-js-misc\04-reference-type\3-why-this\task.md
D:\js\es.javascript.info\1-js\99-js-misc\04-reference-type\3-why-this\solution.md

task.md , ok - (cant remember, either goes staged or shows conflict, but it IS OK).
solution.md - goes straight to the merge like no 3way is there.  

I'm a novice on git.  Coudnt find any useful from git log
I guess I'll put an issue?

**Comment by joaquinelio** [comment]
LOVE IT ❤️ 

1) Yes, Valentina vplentinax DID A LOT.  She pushed the repo ahead, translations and reviews.

2) I like this too
According to your browser headers, you know English. Please help to translate the tutorial. Thank you!

We could use some new blood

3) "about" 
HEY! Don't encourage TRANSLATORS only.
we need REVIEWERS, the hard part.
But it's ok, I was chasing people with solid background among them. It payed well.

I can die now. ✌️

**Comment by iliakan** [comment]
> Pulling from English upstream tries to OVERWRITE SOME traslated files. NO conflicts shown.
> but some files are replaced by english version with no conflict at all
@joaquinelio Such thing may happen, I think I saw it too once, but don't remember what's causing it. I'd like to check out an example.

**Comment by EzequielCaste** [comment]
> I enabled CI, so any pushes to this repo get to the site automatically.

Merged an article yesterday: [Capturing groups #345](https://github.com/javascript-tutorial/es.javascript.info/blob/master/9-regular-expressions/11-regexp-groups/article.md)

Online version has not been updated. Does this take some time? or is the update automatic?

**Comment by iliakan** [comment]
@EzequielCaste sorry, my typo, now should work =)

**Comment by EzequielCaste** [comment]
Thank you @iliakan 🙏 
One last favor I ask from you today...

since I changed my username, the Issue #17 Information gets overwritten:

> Maintainer List
> @lizzie136, @vplentinax, @ezzep66, @joaquinelio, @maksumi 


can you please update my data?
I think the bot overwrites with original username, it should be @EzequielCaste

**Comment by iliakan** [comment]
Added maintainers at https://es.javascript.info/about =)

**Comment by iliakan** [comment]
Please translate this:

[es.yml.zip](https://github.com/javascript-tutorial/es.javascript.info/files/5072780/es.yml.zip)

**Comment by joaquinelio** [comment]
ok I'm on it.  ✍️

**Comment by joaquinelio** [comment]
Last line: "tutorial -is- English"?

hey pals:  @EzequielCaste , @maksumi 

dash - ¿","? Not natural.  Not happy.  Queda un poco forzado.
maintainer ... ==  ¿Mantenedor? prefero el título github!
markup	... ==
[es.yml.zip](https://github.com/javascript-tutorial/es.javascript.info/files/5073922/es.yml.zip)

**Comment by iliakan** [comment]
@joaquinelio what's wrong with the last line? It just states that the Spanish version is a translation of the English one.

By the way, do you know that you can translate text in images too?
For example, here:
![image](https://user-images.githubusercontent.com/349336/90239051-9bfb7a80-de2f-11ea-81ce-5ebedafd25b7.png)

We use SVG format for images, so no need to use graphics editor for that. Just translate the text.
Here are the details: https://github.com/javascript-tutorial/server#translating-images

**Comment by iliakan** [comment]
@joaquinelio is the `es.yml.zip` from your message a finished translation? or I'd better wait?

**Comment by joaquinelio** [comment]
1)  SVG, 
I know that, I read about tha yaml  in the server readme.  It's Sad magicimg (or something) is not working for me yet.  I'm dealing with the pull issue now.

2) yaml Last line
"This is the translated version of the tutorial is English"
sound odd

3) to wait or not to wait...
It depends. 
Nothing too wrong, it's good enough. 
But It doesnt seem urgent, no need to waste time, just a check.

**Comment by iliakan** [comment]
2. Maybe I should rephrase it?
3. Ok, I'll wait then.

**Comment by joaquinelio** [comment]
> 2. Maybe I should rephrase it? 
This is the translated version of the tutorial -in- English, maybe? 
Again, not my language.

**Comment by iliakan** [comment]
Oh, a typo there! Right, corrected 🙄

**Comment by iliakan** [comment]
Thank you so much.

**Comment by iliakan** [comment]
Now I feel stupid for not understanding you.

**Comment by joaquinelio** [comment]
Says the man who created this entire multi-soul project

But it's ok, nobody understands me.
👍

**Comment by EzequielCaste** [comment]
> We use SVG format for images, so no need to use graphics editor for that. Just translate the text.
> Here are the details: https://github.com/javascript-tutorial/server#translating-images

Hi @iliakan I'm trying to install the server, following the instructions above, I get this error after the command `edit es`

[11:01:52] 'webpack' errored after 4.28 s
[11:01:52] ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
 - options[1] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
    at validate (C:\Users\ezzep\js\server\node_modules\copy-webpack-plugin\node_modules\schema-utils\dist\validate.js:96:11)
    at new CopyPlugin (C:\Users\ezzep\js\server\node_modules\copy-webpack-plugin\dist\index.js:24:30)
    at Object.module.exports [as webpack] (C:\Users\ezzep\js\server\modules\config\webpack.js:316:7)
    at Promise (C:\Users\ezzep\js\server\tasks\webpack.js:7:36)
    at new Promise (<anonymous>)
    at module.exports (C:\Users\ezzep\js\server\tasks\webpack.js:6:9)
    at C:\Users\ezzep\js\server\modules\engine\gulp\requireModuleTasks.js:11:12
    at taskWrapper (C:\Users\ezzep\js\server\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:425:14)
    at runBound (domain.js:438:12)
    at asyncRunner (C:\Users\ezzep\js\server\node_modules\async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
[11:01:52] 'edit' errored after 4.28 s

Any thoughts how to solve this?

**Comment by iliakan** [comment]
Please show me the versions:

```
cat node_modules/webpack/package.json | grep '"version"'
cat node_modules/copy-webpack-plugin/package.json | grep '"version"'
```

**Comment by EzequielCaste** [comment]
`
"version": "4.44.1",
"version": "6.0.3"
`

**Comment by iliakan** [comment]
That's strange: `package.json` has "copy-webpack-plugin": "^4.5.2".
So it really should be 4, not 6.

**Comment by EzequielCaste** [comment]
Ok rolled back to original version. I may hay updated the version..

`Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '/img/subscribe_bg.svg' in 'C:\Users\ezzep\js\server\tmp\en'
`

**Comment by EzequielCaste** [comment]
Module `execa` was missing from my modules...

It's working now, at least on my localhost.

**Comment by EzequielCaste** [comment]
ok almost got it...

> /article/coding-style/code-style.svg: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "{\"width\":%w,\"height\":%h}" "C:\Users\ezzep\js\server\public\en\article\coding-style\code-style.svg" this most likely means the gm/convert binaries can't be found

**Comment by joaquinelio** [comment]
@EzequielCaste 
1)
Welcome to the point I quit! 
I guess it lacks PATH entry

2)
Can you please check es.yml.zip from... uhm... comment 5 hours before this? 
Plis don't drop the entire transl... 

[es.yml.zip](https://github.com/javascript-tutorial/es.javascript.info/files/5075347/es.yml.zip)
original
10 hours before this...

it really should show the comment ID

**Comment by maksumi** [comment]
> Last line: "tutorial -is- English"?
> 
> hey pals:  @EzequielCaste , @maksumi 
> 
> dash - ¿","? Not natural.  Not happy.  Queda un poco forzado.
> maintainer ... ==  ¿Mantenedor? prefero el título github!
> markup	... ==
> [es.yml.zip](https://github.com/javascript-tutorial/es.javascript.info/files/5073922/es.yml.zip)
> 

Ponme en contexto @joaquinelio

**Comment by joaquinelio** [comment]
@iliakan
Well, no reviewers for this. 
It's ok, you can use it. Some changes from the last one.
 
[es.yml.zip](https://github.com/javascript-tutorial/es.javascript.info/files/5099428/es.yml.zip)

Anything else to be done here?

**Comment by EzequielCaste** [comment]
Sorry @joaquinelio I didn't quite understand what you meant. 🤷‍♂️ 

We're you waiting for me to review this?

**Comment by EzequielCaste** [comment]
Closing this, since we are ONLINE now and I was able to translate the SVG images.

**Comment by joaquinelio** [comment]
new issue?
 es.js.cx’s server IP address could not be found.

 //es.javascript.info/event-delegation

2.2.3 article.md (still English)
line 14 [iframe height=350 src="bagua" edit link]

buttons:
plunker is working
new window is not:  //es.js.cx/article/event-delegation/bagua/

**Comment by iliakan** [comment]
Should be ok now, is it?

**Comment by joaquinelio** [comment]
that was fast 👍

**Comment by iliakan** [comment]
Please also check out https://es.javascript.info/about
