### ISSUE TITLE
"Biased bot" or "When to show online 'Translation needed' msg"

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#362]
@iliakan ?
Mr Bot failed to follow this article on every step: 1) Comment, 2) PR, 3) Merge

>X Backreferences in pattern: \N and \k (@cortizg) #356

Note: It doesn't show unescaped angle brackets **name** (so cut & paste),  issue source looks:
>[Backreferences in pattern: \N and \k\<name\>]
 
Didn't care.
But I wonder if the online message is related to this: 
"only available in the following langs..."
>"Este material solo está disponible en los siguientes idiomas: عربي, English, 日本語, (...)
Referencias inversas en patrones: \N y \k<nombre>

Now Mr Bot did it again (same user, just funny). Step 1) No thumbs up: 
>Contributor
cortizg commented yesterday
Alternation (OR) |

I guess a regexp issue |  this time?

**Comment by iliakan** [comment]
In the issue text, there's `Backreferences in pattern: \N and \k<name>`, but github "swallows" `<name>`.

* [X] [Backreferences in pattern: \N and \k<name>](https://github.com/javascript-tutorial/es.javascript.info/blob/master/9-regular-expressions/12-regexp-backreferences) (@cortizg) #356

Maybe we need to escape `< >` as `\< \>`:

* [X] [Backreferences in pattern: \N and \k\<name\>](https://github.com/javascript-tutorial/es.javascript.info/blob/master/9-regular-expressions/12-regexp-backreferences) (@cortizg) #356

**Comment by joaquinelio** [comment]
uh... 
I know, 
But it's just git and human reading / cut-pasting, 
anything to do with the online message? The source angle brackets are there.

What about 
>Alternation (OR) |

**Comment by iliakan** [comment]
Ok, so the first issue is with github escaping.

Now about "Este material solo está disponible en los siguientes idiomas" - is anything wrong on the website https://es.javascript.info/ ?

**Comment by joaquinelio** [comment]
The comment only shows on untranslated articles...
and the translated "Backreferences in pattern: \N and \k"
So I wonder how the online site knows when an article needs translation.

Besides that, I dont care helping Don Bot when he needs it.

**Comment by joaquinelio** [comment]
In short
>Now about "Este material solo está disponible en los siguientes idiomas" - is anything wrong on the website https://es.javascript.info/ ?

If anything, the msg and the translation link to **git es...12-regexp-backreferences**
shouldn't be there, it's already translated.

**Comment by iliakan** [comment]
Ok, that's a totally separate issue. Anything else?

**Comment by joaquinelio** [comment]
Nothing else.

ok, I just thought the issues could be related... 
if not, I can't figure out how the message knows when to show up.

thanks

**Comment by iliakan** [comment]
Thanks, I'll fix them ;)

**Comment by iliakan** [comment]
Fixed!
