### ISSUE TITLE
Biased bot. Really.

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#368]
@iliakan 
sorry to bother you again, about your kid.
He keeps unchecking these articles, 
Perhaps considering they need renaming? (note "\\")

![bot](https://user-images.githubusercontent.com/6558304/91874935-30981200-ec51-11ea-8642-f99355b0e916.png)

**Comment by iliakan** [comment]
@joaquinelio Sure thanks, could you explain in few words what has happened?

**Comment by joaquinelio** [comment]
just that, 3 translated articles, I check them, then bot unchecks.
 
I guess it is because of the \\ considering they need to be renamed.

No right in the moment I check them, but when "he" goes to edit some other thing,
last time in the moment an article was taken

all at once the bot:
* Added user (@EzequielCaste)  to article "indexedDB" 
* Removed [X] from 3 articles: (maybe renamed because it erases @ user and  # PR too) 
-Unicode: flag "u" and class \p{...}
-Word boundary: \b
-Backreferences in pattern: \N and \k<name>

the 3 with a backslash 
the 3 from @cortizg , I guess just a funny coincidence

**Comment by joaquinelio** [comment]
...oops he did it again
@iliakan , Don Bot needs vacation

User mariomenjr took an article, 
then  Bot modified issue17. Again, in a single update :  

1) Added user to the article, OK:
[ ] ArrayBuffer, binary arrays (@mariomenjr)

2) Removed [X] from the same 3 articles:  
-Unicode: flag "u" and class \p{...}
-Word boundary: \b
-Backreferences in pattern: \N and \k

I know it's him.  It's recorded in the issue17 update history.
![image](https://user-images.githubusercontent.com/6558304/92086729-f76eb780-eda0-11ea-808b-c3ae4ffdffc0.png)

![0002](https://user-images.githubusercontent.com/6558304/92086917-37ce3580-eda1-11ea-87f6-44af0d453d07.png)

Though I couldn't get issue history via API.

(Bot is failing in adding PR to the issue too, -mariomenjr Bubbling and capturing #372- but I dont care)

**Comment by iliakan** [comment]
I didn't fix it yet, quite a lot of debugging after putting escapes in.

**Comment by joaquinelio** [comment]
ah, ok, I though you didnt believe me, sorry =)
it's not a fatal err anyway, I'll put the X X X back.

**Comment by joaquinelio** [comment]
There is a step Mr Bot miss: 

Translator claims (valid) - OK
Translator claims (taken) - OK
Translator put a PR -   ?
Maint. merge a PR - OK

The problem started before your big fix, I didn't mind too much. 
The important issue is solved 👍 

Example:
https://github.com/javascript-tutorial/es.javascript.info/pull/374
[The clickjacking attack] | (@homero304) | 2020-09-01 | #374

**Comment by iliakan** [comment]
@joaquinelio Again, what's the problem exactly? 

This looks perfectly fine:
![image](https://user-images.githubusercontent.com/349336/92640663-4dce7f80-f2e6-11ea-9626-360b64c31441.png)

Or did you fix anything manually?

**Comment by iliakan** [comment]
I'd like to fix that.

You mean that when translator puts a PR - nothing happens?

**Comment by joaquinelio** [comment]
Exactly.

Thats why I put the verified example.  
Other times they dont match case, sometimes the PR is renamed after, so it's ok they miss.

**Comment by iliakan** [comment]
@joaquinelio Thank you. That's because people developing @octokit/rest just LOVE to rename methods with every release. Like no one.

I updated the method call, should work now ;)

**Comment by iliakan** [comment]
Thank you for precise explanations of the errors :)

**Comment by joaquinelio** [comment]
Experience.
I dont believe users either 🤞
