### ISSUE TITLE
Formato incorrecto

### ISSUE THREAD

**Issue by nPuBuDeHuE** [javascript-tutorial/es.javascript.info#371]
La pagina https://es.javascript.info/logical-operators tiene el formato incorrecto en el artículo "NO"

![js-learn-es-NO](https://user-images.githubusercontent.com/20505410/91982241-60bfdd80-ed43-11ea-9e49-7cb2f46fdb3e.JPG)

**Comment by EzequielCaste** [comment]
Ok gracias por informarnos.

**Comment by joaquinelio** [comment]
Git no soporta markup anidados

La unica manera de revisar formatos es probando con el server local

@EzequielCaste despues me podes XXXXX porque hace 5 dias hice un commit sin doble revision, 
aunque la causa era linea 225 que parece que estaba de antes

hice un patch de emergencia cierro.

**Comment by EzequielCaste** [comment]
Soltar ...

**Comment by nPuBuDeHuE** [comment]
Gracias

ср, 2 сен 2020 г., 21:28 Ezequiel Castellanos <notifications@github.com>:
