### ISSUE TITLE
Mr. Bot Sync PR- How it shows conflicts.  

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#387]
@iliakan 
There are many conflicts in those files, #383
but the only one GIT treats as a conflict is the one recently added in the last ES merge,
the only one that disabled the merge button.

>This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
2-ui/99-ui-misc/02-selection-range/article.md

It would be nice to have the GITHUB conflicts tools for easy fixing all the conflicts,
but more important, without them you may miss changes and...
accidentally merge the files with >>> === <<< stuff ?
 
Can this be improved?
Just to know and spread the warning
@vplentinax @EzequielCaste @maksumi @lizzie136

**Comment by iliakan** [comment]
For me, the "resolve" button is enabled:
![Uploading image.png…]()

**Comment by joaquinelio** [comment]
I tried to show you the difference, I failed.
The resolve is only there for the ONE file merged AFTER the PR,
is not working for the 33 ones Mr.Bot found.

You can see it right there, 
"Conflicting files" 
2-99-2-selection-range  
...
One file. 

If I resolve it, merge will be enabled again.

**Comment by joaquinelio** [comment]
Here.
I resolved OUR little conflict,   
MERGE is enabled again 

![image](https://user-images.githubusercontent.com/6558304/94025518-f7a21780-fd8e-11ea-90b1-cbada16f9d80.png)

**Comment by joaquinelio** [comment]
Merge works, I dangerously pressed it... then cancel.
I put it as draft now.

**Comment by joaquinelio** [comment]
github somehow treats it as normal text,
I guess merge would add >>>> ==== stuff to the files.
something is missing.

**Comment by joaquinelio** [comment]
That's it.

Git is right, There are NO conflicts at all

If I MERGE, (dont worry I didnt)

NEW lines will be added, ZERO conflicts. 
Those lines are yours and will not overwrite anything, 
it will add odd lines 

+ "<<<<<<< HEAD"
old spanish untouched text
+ "======
+ "new english text...
+ "new english text...
+ "new english text...
+ "new english text...
+ ">>>>>>  branch"

**Comment by joaquinelio** [comment]
We can still safely use bot's PR,
We just need to pay MUCH attention in edition
