### ISSUE TITLE
Add the hacktoberfest topic to repository

### ISSUE THREAD

**Issue by Arnau-Ninerola** [javascript-tutorial/es.javascript.info#399]
Me gustaría ayudar a traducir y corregir algunas de las secciones. Estoy participando en la Hacktoberfest y para que estos pull requests me cuenten como válidos necesitas añadir "hacktoberfest" como tópico del repositorio. Si lo añades voy a hacer mas contribuciones y es una buena manera para que venga más gente a ayudar.

Aquí cómo hacerlo: https://hacktoberfest-assets.nyc3.cdn.digitaloceanspaces.com/hacktoberfest-eligible-gif.gif

**Comment by joaquinelio** [comment]
Todos son bienvenidos a colaborar...
pero creo más en el incentivo altruista que el de un premio dado por una empresa comercial que usa  plataformas open source.

¿Alguien tiene alguna  conocimiento u opinión sobre esto?
No me siento con autoridad para cerrarlo, pero no tengo ganas de aumentar el riesgo de PR descuidados.... Y la carga de los maintainers.

**Comment by Arnau-Ninerola** [comment]
Aunque entiendo perfectamente tu razonamiento, Hacktoberfest es un evento que se realiza cada octubre y ya llevan 7 años haciéndolo. Es una buena manera para atraer a gente a colaborar en proyectos o para hacer conocer el mundo de open source a aquellos programadores principiantes, intentando hacer que se sienten cómodos y motivándolos a colaborar. 

¿Si el fin es que se realicen más contribuciones a este u otros proyectos open source, cuál es el problema? Yo he colaborado previamente a este proyecto varias veces, pero también me gusta mucho lo que hacen cada año en Hacktoberfest, ya no solo por el premio (que es una simple camiseta o incluso puedes decidir que planten un árbol por ti) sino para sentirme parte de una comunidad, aquí en mi ciudad se realizan eventos cada octubre para celebrar el open source. 

Además, que una vez terminado el mes de octubre se puede quitar el tópico.

**Comment by maksumi** [comment]
Hola @Arnau-Ninerola. Mil gracias por la propuesta.
Honestamente, y de manera abierta lo digo, todo iba bien hasta que entró la condicional: "si lo añades voy a hacer más contibuciones". Justo en ese punto entra lo que comenta @joaquinelio, todos son bienvenidos a colaborar, pero justo al ser un proyecto OS que después de haber estado estancado un buen tiempo llegó mucha gente sin saber bien sin idea realmente de la responsabilidad que implica aún cuando sea contribución voluntaría, creo que existe el riesgo de que no tome la seriedad que ocupa justo por el hecho de que muchos empiezan a hacer sus pininos en open source. Aún gente con más experiencia en el ramo, que ya vive de esto, llega y deja votado el proyecto, y aunque se agradece la voluntad creo que también importa la responsabilidad y el compromiso con el proyecto. Dentro de lo posible, por mi parte y en lo que mis posibilidades me lo permiten así como cada uno de los maintainers, justo se ha tratado de generar ese ambiente comunitario con cada nuevo miembro. 

**Como conclusión:** No veo mal la organización del fest como incentivo a que los nuevos en este mundo se animen a buscar proyectos para colaborar en open source, pero no creo que sea la motivación o la condicional para colaborar en este proyecto. 

**_Esto es meramente mi opinión, no representa ninguna decisión absoluta respecto al tema, creo que habrá que ver qué piensan @vplentinax @EzequielCaste y @lizzie136  también. Por otro lado, en todo caso creo que el lugar más apto para hacer esa solicitud sería con Iliankan en el proyecto originial en inglés_**

**Comment by vplentinax** [comment]
Concuerdo con @maksumi  y @joaquinelio . Al decir "si lo añades"... nos condicionas. Si desean colaborar, lo pueden hacer abiertamente. De resto, habla personalmente con @iliakan  en su repositorio original, que es el de inglés. @Arnau-Ninerola

**Comment by Arnau-Ninerola** [comment]
Hola @maksumi, entiendo perfectamente lo que dices y puede que la manera en la que lo escribí de a malinterpretaciones, así que voy a intentar explicarme mejor. A lo que me refería es que con el actual evento pues quiero dedicar mi tiempo este mes en contribuir a repositorios que cuenten para Hacktoberfest. Evidentemente todos disponemos de tiempo limitado y estamos ocupados, pero sí quiero participar así que quiero dedicar mis esfuerzos este mes para eso. 

Con esto no quiero decir que no vaya a contribuir, no estoy intentando condicionar a nadie. Porque si lo voy a hacer, como ya he hecho en varias ocasiones previamente. Además de dar más visibilidad a los proyectos open source, el evento también tiene como objetivo la calidad de las contribuciones y no solamente hacer pequeños cambios. Es por eso que los pull requests no son válidos para el evento hasta que son aceptados, y cuenta con herramientas como marcar los pull reuquests como spam. 

Yo también digo honestamente y solo siendo mi opinión, sin intentar criticar a nadie ni al proyecto, que más pull requests con contribuciones siempre es mejor a que el proyecto esté estancado durante un largo periodo, entendiendo también que eso conlleve más trabajo a los mantainers, ya que algunos pr serán de baja calidad.

Gracias por vuestras opiniones, hablaré con @iliakan

**Comment by iliakan** [comment]
Done.

**Comment by joaquinelio** [comment]
Hi @iliakan 
Do you know about the project?  
We 3 didn't discuss this, but the 3 separately opined against it so no one added the topic.

I want to contribute to open source and any festivity related to, but I don't have the extra time.
Yes, maybe we are selfish.
 
Anyway the risk of "spam" entire translation is very, veeeery low =)

**Comment by iliakan** [comment]
@joaquinelio As I understand it, the tag is needed for hacktoberfest people to contribute. And that's all, it doesn't force us into anything.

Is that correct?

**Comment by joaquinelio** [comment]
What we need is reviews, and maybe this attract some. fixing typos mostly.

**Comment by Arnau-Ninerola** [comment]
That's correct @iliakan , this tag is only needed for people participating in it, that is all. Everything else works the same as always.

**Comment by joaquinelio** [comment]
@iliakan 
-Previous comment wasnt not related to your question.-

I dont know. I was open to it, I didnt research too much. 
I was afraid of the extra work and low quality PR.
We need more committed work

It's just a feeling. 
Seems nice, but how DigitalOcean contributes?  Just adding extra work to unpaid maintainers. 
So I asked for opinions.

**Comment by joaquinelio** [comment]
"After some discussion, they have indicated to me..."
Ha ha!! 
that was't very honest...
"some discussion" we opined against.  

You may fix this @Arnau-Ninerola, doing some commited work on november 

Welcome to the repo.
=)

**Comment by EzequielCaste** [comment]
All I've heard from the web is that there are many people complaining about many randon nonsense (not really contributing) PRs due to this hacktoberfes thing.

The spam the PRs with comments and that way they "earn points" for a hacktober fest t-shirt....

Not worth it.
IMO

**Comment by Arnau-Ninerola** [comment]
@EzequielCaste well it is true that it might bring some spam, but that could happen without the event going on. I still believe that having more people contributing to the project is a good thing. On the other hand, PRs that are spam and are not merged **DONT** count to earing points or anything. Hacktoberfest has very clear rules that on top of everything they want quality not quantity.

@joaquinelio Yes, you were against it, but all your comments said that I should ask this directly with the english repo, that is what I did and he agreed. It was honest, we were discussing about it, weren't we? I understand that this _may_ bring more work, I want to help if it's needed.

As I have said, I will be contributing to this project, and not only in October, because I really like it and because I think it's very useful to have it in more languages for new beginners to learn. As I have mentioned, I have previously have merged commits to this project and the catalan version :)

**Comment by joaquinelio** [comment]
"all the comments" untrue.

Again.  It's ok. But 
the risk falls on us,
we were discussing it, 
and you didnt mention "against" in "discussing it"  : (

I just don't know enough about the project and consequences.
Again, it may be good.

hahaha!
We spent more time with this than with the spam it surely will not come.

enjoy the festivity
=)

**Comment by Arnau-Ninerola** [comment]
I understand that you may have an increased workload with low effort PRs. That is not my intention. Thanks for considering that it can be good. 

> We spent more time with this than with the spam it surely will not come.
Yes! You are right. Thanks again, I enjoy this yearly event :D

**Comment by iliakan** [comment]
Well, guys, let's just see what happens ;)

**Comment by iliakan** [comment]
I personally have no expectations good or bad, just never had experience with hacktoberfest.

**Comment by joaquinelio** [comment]
Should we add "contributors wanted" somewhere?
Is it automatically listed somewhere?
Didnt read about.

**Comment by joaquinelio** [comment]
I'm not against "low level PR" and I dont want to mention it this way, 
we all start low and we all may have some flaws, then improve with the help of the community. 
Visibility is a good thing, I was just uncomfortable with quality related to the motivation.

**Comment by iliakan** [comment]
@EzequielCaste @joaquinelio @maksumi @vplentinax I'm sorry I didn't read the discussion in this issue.

My Spanish is only basic, I mostly rely on google translate. So I was mentioned, came here and only read the original request.

For us, the quality is the basic requirement, that's for sure.

Still, I suppose we can remove the tag any time, right? Quite an easy thing to do.

Also, I guess hacktoberfest is mostly for software development, not for writing a tutorial how to do it. We're a different type of project. So I don't expect spam PRs. Actually, I don't expect any effect from that, but let's see, why not, there's no risk.

**Comment by joaquinelio** [comment]
It's ok
I was reading some.
I agree, it will have little impact here. Unless we gain more visibility.  

We are exposed anyway.  If you look for points you need : 
tag and approved PR , 
OR  approved PR with hacktoberfest specific name. 

The spirit is good, most of developers there participate with enthusiasm. 
But some may be looking for easy points,  a PR fixing a typo is enough, explicit rules.

If you are curious, take a quick look at  https://dev.to/t/hacktoberfest comments page. It is more realistic than the sponsor site.
I wish I had something like this when younger. and with time to spend.
The general feeling is like this:
"...can be a lot of fun. It can also be a lot of work."
Lots of work, means maintainers.

Problem here: Sponsor is a commercial site. They encourage open source "go and have fun" 
but uses free resources for its campaign
I've got Azure free account, but no Digital Ocean cloud. buuuuuh!!

**Comment by maksumi** [comment]
Dejando atrás los malentendidos y pensando esto en pro bilateral, te animamos a tomar un **artículo entero** sin traducir de [la lista](https://github.com/javascript-tutorial/es.javascript.info/issues/17). También **te damos la bienvenida al repo en español**, te invitamos a darte una vuelta por el **README** del repo y a que ingreses al **Discord** del equipo (encontrarás el link en el README) para que te presentes con los demás participantes y recibas y des apoyo en cualquier sugestión.

**Comment by iliakan** [comment]
For the English repo I started to see really bad quality PRs. I guess it may be the result of the hacktoberfest, so I removed it thre and here too.

P.S. Actually, this tag isn't needed. A merged PR labelled with hacktoberfest-accepted counts too for them.

**Comment by Arnau-Ninerola** [comment]
I think that's smart to remove it then. Since bad quality PRs ruin the experience and add a lot more work to you guys. And what you say is true, adding the label "hacktoberfest-accepted" works as well too. Anyways it's not many days left in the month but if anyone wants their PRs to count should we just ask the maintainers to add them with a comment on the PR?

**Comment by iliakan** [comment]
If the PR is worthy and merged, then we can add the label. As of now, looks like all PRs are crappy (for English).

**Comment by joaquinelio** [comment]
It's ok.  
The stubborn Arnau did good 👍 

I didn't like the origins. It's a big campaign from Digital-Ocean, it gets a lot of attraction for free.
I read about, all the burden falls in open source maintainers and the company does nothing.

Coders, they look happy. I wish I was half century younger.
