### ISSUE TITLE
Actualizar: 1-3-6-article polyfills fue reescrito en inglés  

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#457]
Muchos cambios, pero es un art muy corto (un centenar de lineas)

**Comment by matiasfha** [comment]
Yo puedo revisarlo!

**Comment by joaquinelio** [comment]
uh, lo terminé.  
No es que estuviera apurado, habiendo tantos issues podría haberme puesto a hacer cualquier otro.
@matiasfha
