### ISSUE TITLE
[ ]( mdn:... ) format, spanish ruined.

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#476]
Hi @iliakan 

`prototype-inheritance   290...    [](  mdn:js/Object/hasOwnProperty  ) `

tries to go to
https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty
you get:

```
Good news!
The page you requested doesn't exist in Spanish but it exists in English
Object.prototype.hasOwnProperty()
/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty
```

Now, once there, you CAN select ES, 
but the url is translated too !!!  
".../Referencia/Objetos_globales/..."  
https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Object/hasOwnProperty

any... idea? 

___
more info

* still works on several links like `(mdn:api/Window/prompt)`

* but it seems translators screwed the "Reference" branch
Is MDN commited to the format or it was just you liked the beauty of the idea? It "was" a good idea... :(

* "not found" 
Other links give "not found" (mdn message)
A link I tested before ` mdn:/JavaScript/Reference/Global_Objects/DateTimeFormat  `
with NO spanish translation, 
now it gives "not found" instead of  going to /en-US/  version
https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat 
I have to manually replace
/es/ with /en-US/

**Comment by iliakan** [comment]
Just insert the full URL?

**Comment by joaquinelio** [comment]
buh...  hoped for magic
It worked pretty well while worked...

**Comment by joaquinelio** [comment]
@vplentinax 
formato link [ ... ](mdn: ...  )  no es confiable, hay que testear y traducir a full link

Antes, si fallaba EsP saltaba al ENG (admito que probé mal, podría haber habido esp que igual no se encontrara),  
Pero ahora, haya o no traduccion, los links que no coinciden dan error.

* Muchos aún funcionan.
* Definitivamente fallan  los   .../Javascript/Reference/... , hay 22   ***veré*** 
* En total son 158, que no voy a probar... "pronto".
