### ISSUE TITLE
corrección Page: DOMContentLoaded, load, beforeunload, unload

### ISSUE THREAD

**Issue by mattdimicelli** [javascript-tutorial/es.javascript.info#518]
En este artículo está escrito: "En el ejemplo, el controlador DOMContentLoaded....."

Opino que debería ser "En el ejemplo, el controlador de DOMContentLoaded....."

**Comment by joaquinelio** [comment]
Gracias!

Aproveché para arreglar otra cosa en el mmo renglon, ("se carga" vs "terminó de cargarse")  

y para mandar la inquietud al repo ingles:
 
the X handler => el manejador X
vs
the X's handler
the handler of X

**Comment by joaquinelio** [comment]
Y ya me la rechazó.

jaja!
pero aca quedo bien ahora.
