### ISSUE TITLE
lost in translation: built-in  traduccion no unificada. ¿Incorporado?

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#654]
***se tradujo por "incorporado", "integrado" y "nativo"***

incorporado significa "añadido", lo opuesto a built-in. Una biblioteca de 3ros tamb incorpora funciones.
integrado no resuelve el problema de ambig¨uedad.
nativo es certero, pero muy poco usado y quizas confunda.

***Propuesta 1 "preincorporado"***
demasiado aparatoso, pero preciso y entendible por TODOS

***Propuesta 2... "incorporado", porque lo dice MDN***
No usabamos MDN-ES como referencia de traduccion porque hace años tenia muchas burradas
Pero mejoro mucho, y por el bien de la estandarizacion es quiza la mejor opcion para unificar.

**Comment by maksumi** [comment]
Hey @joaquinelio! Maksumi is in da house. ¿
Por dónde nos podemos comunicar para ponerme al corriente, amigo?

**Comment by joaquinelio** [comment]
alex!

ando algo perdido, olvide que pediste contactar por discord

Tambien ando gagá
No me funcionan las alarmas.
Este issue ya lo habia hecho, pero cuando lo escribi me parecia una novedad asi que he de cerrarlo...
