### ISSUE TITLE
Traducción

### ISSUE THREAD

**Issue by Jarguez** [javascript-tutorial/es.javascript.info#666]
Yo puedo contribuir con la trauccion del siguiente artículo:
[Error handling, "try...catch"](https://github.com/javascript-tutorial/es.javascript.info/blob/master/1-js/10-error-handling/1-try-catch)

**Comment by joaquinelio** [comment]
Ya no queda nada por traducir @Jarguez 

Podrías colaborar, si ves alguna corrección que quieras hacer mandando un PR.
