### ISSUE TITLE
Online Spanish site not in sync with repo

### ISSUE THREAD

**Issue by joaquinelio** [javascript-tutorial/es.javascript.info#719]
Hi, @iliakan 

2 days ago merge is not online

**Comment by joaquinelio** [comment]
@smith558 maybe?

**Comment by smith558** [comment]
> @smith558 maybe?

I noticed it takes about 5 or even more days on average for changes to propagate. I don't know exactly what causes it, something in the deployment pipeline. @iliakan has more insight.

**Comment by iliakan** [comment]
Thanks for mentioning me! Investigating.

**Comment by iliakan** [comment]
I think our administrator @amaxcz fixed the issue! ;) 
Thanks, @amaxcz !

**Comment by iliakan** [comment]
Closing it for now, please reopen if the problem appears again.

**Comment by joaquinelio** [comment]
Thank you all!
